"""empty message

Revision ID: 17024207063f
Revises: fcefcef011d4
Create Date: 2022-06-20 13:43:34.389741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17024207063f'
down_revision = 'fcefcef011d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parent')
    op.add_column('child', sa.Column('family_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.create_foreign_key(None, 'child', 'family', ['family_id'], ['id'])
    op.drop_column('child', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.create_foreign_key(None, 'child', 'parent', ['parent_id'], ['id'])
    op.drop_column('child', 'family_id')
    op.create_table('parent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('family')
    # ### end Alembic commands ###
